import { Order } from "@/types";

export const orders: Order[] = [
  {
    customerId: 6,
    orderDate: "2019-01-30",
    status: 1,
    comments: null,
    shippedDate: null,
    shipperId: null,
  },
  {
    customerId: 7,
    orderDate: "2018-08-02",
    status: 2,
    comments: null,
    shippedDate: "2018-08-03",
    shipperId: 4,
  },
  {
    customerId: 8,
    orderDate: "2017-12-01",
    status: 1,
    comments: null,
    shippedDate: null,
    shipperId: null,
  },
  {
    customerId: 2,
    orderDate: "2017-01-22",
    status: 1,
    comments: null,
    shippedDate: null,
    shipperId: null,
  },
  {
    customerId: 5,
    orderDate: "2017-08-25",
    status: 2,
    comments: "",
    shippedDate: "2017-08-26",
    shipperId: 3,
  },
  {
    customerId: 10,
    orderDate: "2018-11-18",
    status: 1,
    comments: "Aliquam erat volutpat. In congue.",
    shippedDate: null,
    shipperId: null,
  },
  {
    customerId: 2,
    orderDate: "2018-09-22",
    status: 2,
    comments: null,
    shippedDate: "2018-09-23",
    shipperId: 4,
  },
  {
    customerId: 5,
    orderDate: "2018-06-08",
    status: 1,
    comments:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
    shippedDate: null,
    shipperId: null,
  },
  {
    customerId: 10,
    orderDate: "2017-07-05",
    status: 2,
    comments: "Nulla mollis molestie lorem. Quisque ut erat.",
    shippedDate: "2017-07-06",
    shipperId: 1,
  },
  {
    customerId: 6,
    orderDate: "2018-04-22",
    status: 2,
    comments: null,
    shippedDate: "2018-04-23",
    shipperId: 2,
  },
];
