import { Customer } from "../../types";

export const customers: Customer[] = [
  {
    customerID: 1,
    firstName: 'Chris',
    lastName: 'Dixon',
    address: '212 N Rose St',
    city: 'Lakewood',
    state: 'CO',
    zip: '80215',
    country: 'USA',
  },
  {
    customerID: 2,
    firstName: 'David',
    lastName: 'Power',
    address: '44 Wiley St',
    city: 'Henderson',
    state: 'NV',
    zip: '89002',
    country: 'USA',
  },
  {
    customerID: 3,
    firstName: 'Arnold',
    lastName: 'Hinchcliffe',
    address: '7333 E Levine St',
    city: 'Atlanta',
    state: 'GA',
    zip: '30303',
    country: 'USA',
  },
  {
    customerID: 4,
    firstName: 'Keanu',
    lastName: "O''Ward",
    address: '415 N Hinson St',
    city: 'Madison',
    state: 'WI',
    zip: '53703',
    country: 'USA',
  },
  {
    customerID: 5,
    firstName: 'Lisa',
    lastName: 'Rosenqvist',
    address: '56 S Burnett St',
    city: 'Reston',
    state: 'VA',
    zip: '20190',
    country: 'USA',
  },
  {
    customerID: 6,
    firstName: 'Maggie',
    lastName: 'Ilott',
    address: '111 Fuson St',
    city: 'Flagstaff',
    state: 'AZ',
    zip: '86015',
    country: 'USA',
  },
  {
    customerID: 7,
    firstName: 'Cora',
    lastName: 'Daly',
    address: '55 S Brandt St',
    city: 'Anaheim',
    state: 'CA',
    zip: '92802',
    country: 'USA',
  },
  {
    customerID: 8,
    firstName: 'Dan',
    lastName: 'Wilson',
    address: '29 W Pousson St',
    city: 'Seattle',
    state: 'WA',
    zip: '98104',
    country: 'USA',
  },
  {
    customerID: 9,
    firstName: 'Kelly',
    lastName: 'Wheldon',
    address: '300 Dewsnup St',
    city: 'Boise',
    state: 'ID',
    zip: '83703',
    country: 'USA',
  },
  {
    customerID: 10,
    firstName: 'Bhaskar',
    lastName: 'Palou',
    address: '3443 E Ramella St',
    city: 'Evansville',
    state: 'IN',
    zip: '47702',
    country: 'USA',
  },
  {
    customerID: 11,
    firstName: 'Kevin',
    lastName: 'Daly',
    address: '123 Terry St',
    city: 'Rochester',
    state: 'NY',
    zip: '02345',
    country: 'USA',
  },
  {
    customerID: 12,
    firstName: 'Jordan',
    lastName: 'Ericsson',
    address: '187 E Boich St',
    city: 'Gilbert',
    state: 'AZ',
    zip: '85296',
    country: 'USA',
  },
  {
    customerID: 13,
    firstName: 'Ming',
    lastName: 'Zhou',
    address: '42 S Walsh St',
    city: 'Portsmouth',
    state: 'NH',
    zip: '03801',
    country: 'USA',
  },
  {
    customerID: 14,
    firstName: 'Jack',
    lastName: 'Sato',
    address: '242 S Corbett St',
    city: 'Burlington',
    state: 'VT',
    zip: '05401',
    country: 'USA',
  },
  {
    customerID: 15,
    firstName: 'Joe',
    lastName: 'Pagenaud',
    address: '59 E Fleming St',
    city: 'Detroit',
    state: 'MI',
    zip: '48202',
    country: 'USA',
  },
  {
    customerID: 16,
    firstName: 'Tara',
    lastName: 'Di Silvestro',
    address: '789 N Kizer St',
    city: 'San Diego',
    state: 'CA',
    zip: '92101',
    country: 'USA',
  },
  {
    customerID: 17,
    firstName: 'Sandra',
    lastName: 'Calderon',
    address: '5 W Delany St',
    city: 'Denver',
    state: 'CO',
    zip: '80014',
    country: 'USA',
  },
  {
    customerID: 18,
    firstName: 'Margaret',
    lastName: 'Montoya',
    address: '48 Clark St',
    city: 'Monterey',
    state: 'CA',
    zip: '93940',
    country: 'USA',
  },
  {
    customerID: 19,
    firstName: 'Monica',
    lastName: 'Newgarden',
    address: '99 Lynn St',
    city: 'Clayton',
    state: 'MO',
    zip: '63105',
    country: 'USA',
  },
  {
    customerID: 20,
    firstName: 'Mia',
    lastName: 'Rossi',
    address: '276 N Morrison St',
    city: 'Orlando',
    state: 'FL',
    zip: '32801',
    country: 'USA',
  },
];
