import { Employee } from "@/types";

export const employees: Employee[] = [
  {
    employeeId: 37270,
    firstName: "Yovonnda",
    lastName: "Magrannell",
    jobTitle: "Executive Secretary",
    salary: 63996,
    reportTo: null,
    officeId: 10,
  },
  {
    employeeId: 33391,
    firstName: "D'arcy",
    lastName: "Nortunen",
    jobTitle: "Account Executive",
    salary: 62871,
    reportTo: 37270,
    officeId: 1,
  },
  {
    employeeId: 37851,
    firstName: "Sayer",
    lastName: "Matterson",
    jobTitle: "Statistician III",
    salary: 98926,
    reportTo: 37270,
    officeId: 1,
  },
  {
    employeeId: 40448,
    firstName: "Mindy",
    lastName: "Crissil",
    jobTitle: "Staff Scientist",
    salary: 94860,
    reportTo: 37270,
    officeId: 1,
  },
  {
    employeeId: 56274,
    firstName: "Keriann",
    lastName: "Alloisi",
    jobTitle: "VP Marketing",
    salary: 110150,
    reportTo: 37270,
    officeId: 1,
  },
  {
    employeeId: 63196,
    firstName: "Alaster",
    lastName: "Scutchin",
    jobTitle: "Assistant Professor",
    salary: 32179,
    reportTo: 37270,
    officeId: 2,
  },
  {
    employeeId: 67009,
    firstName: "North",
    lastName: "de Clerc",
    jobTitle: "VP Product Management",
    salary: 114257,
    reportTo: 37270,
    officeId: 2,
  },
  {
    employeeId: 67370,
    firstName: "Elladine",
    lastName: "Rising",
    jobTitle: "Social Worker",
    salary: 96767,
    reportTo: 37270,
    officeId: 2,
  },
  {
    employeeId: 68249,
    firstName: "Nisse",
    lastName: "Voysey",
    jobTitle: "Financial Advisor",
    salary: 52832,
    reportTo: 37270,
    officeId: 2,
  },
  {
    employeeId: 72540,
    firstName: "Guthrey",
    lastName: "Iacopetti",
    jobTitle: "Office Assistant I",
    salary: 117690,
    reportTo: 37270,
    officeId: 3,
  },
  {
    employeeId: 72913,
    firstName: "Kass",
    lastName: "Hefferan",
    jobTitle: "Computer Systems Analyst IV",
    salary: 96401,
    reportTo: 37270,
    officeId: 3,
  },
  {
    employeeId: 75900,
    firstName: "Virge",
    lastName: "Goodrum",
    jobTitle: "Information Systems Manager",
    salary: 54578,
    reportTo: 37270,
    officeId: 3,
  },
  {
    employeeId: 76196,
    firstName: "Mirilla",
    lastName: "Janowski",
    jobTitle: "Cost Accountant",
    salary: 119241,
    reportTo: 37270,
    officeId: 3,
  },
  {
    employeeId: 80529,
    firstName: "Lynde",
    lastName: "Aronson",
    jobTitle: "Junior Executive",
    salary: 77182,
    reportTo: 37270,
    officeId: 4,
  },
  {
    employeeId: 80679,
    firstName: "Mildrid",
    lastName: "Sokale",
    jobTitle: "Geologist II",
    salary: 67987,
    reportTo: 37270,
    officeId: 4,
  },
  {
    employeeId: 84791,
    firstName: "Hazel",
    lastName: "Tarbert",
    jobTitle: "General Manager",
    salary: 93760,
    reportTo: 37270,
    officeId: 4,
  },
  {
    employeeId: 95213,
    firstName: "Cole",
    lastName: "Kesterton",
    jobTitle: "Pharmacist",
    salary: 86119,
    reportTo: 37270,
    officeId: 4,
  },
  {
    employeeId: 96513,
    firstName: "Theresa",
    lastName: "Binney",
    jobTitle: "Food Chemist",
    salary: 47354,
    reportTo: 37270,
    officeId: 5,
  },
  {
    employeeId: 98374,
    firstName: "Estrellita",
    lastName: "Daleman",
    jobTitle: "Staff Accountant IV",
    salary: 70187,
    reportTo: 37270,
    officeId: 5,
  },
  {
    employeeId: 115357,
    firstName: "Ivy",
    lastName: "Fearey",
    jobTitle: "Structural Engineer",
    salary: 92710,
    reportTo: 37270,
    officeId: 5,
  },
];
